---
title: Disable Defender
description: Removes Windows Defender components via the Atlas NoDefender CBS package (Atlas OS)
actions:
  - !powerShell:
    command: '.\Install-DefenderPackage.ps1 -InstallPackages ''*Z-Atlas-NoDefender-Package*'''
    option: 'defender-disable'
    exeDir: true
    wait: true
    weight: 100
    runas: trustedInstaller
  - !powerShell:
    command: '.\Install-DefenderPackage.ps1 -UninstallPackages ''*Z-Atlas-NoDefender-Package*'''
    option: 'defender-enable'
    exeDir: true
    wait: true
    weight: 100
    runas: trustedInstaller
