---
title: Hide Meet Now
description: Hides Meet Now tray icon for QoL and privacy (Atlas OS)
actions:
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'
    value: 'HideSCAMeetNow'
    data: '1'
    type: REG_DWORD
