---
title: Remove Microsoft Edge
description: Removes Microsoft Edge and prevents it from being reinstalled (Atlas OS)
actions:
  - !powerShell:
    command: '& """.\RemoveEdge.ps1""" -UninstallEdge -RemoveEdgeData -KeepAppX -NonInteractive'
    runas: currentUserElevated
    wait: true
    exeDir: true
    # AppX uninstallation in the script seems to fail, therefore it's not used and AME Wizard is used instead
    # Note that AppX Edge is removed from the latest builds of Windows, but people could be running a non-updated version
  - !appx: {name: 'Microsoft.MicrosoftEdge_8wekyb3d8bbwe', type: family}
  - !registryKey: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned\Microsoft.MicrosoftEdge.Stable_8wekyb3d8bbwe', operation: add}
  - !registryKey: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned\Microsoft.MicrosoftEdge_8wekyb3d8bbwe', operation: add}
